In [18]:
from pathlib import Path

import numpy as np
import pandas as pd

# galliformes

In [2]:
galliformes_dir = Path("/data-ssd/alex/datasets/vision-export-20221020154449-Galliformes-573/")
galliformes_tax = pd.read_csv(galliformes_dir / "taxonomy.csv")
galliformes_leaf_tax = galliformes_tax[~galliformes_tax.leaf_class_id.isna()]
galliformes_leaf_taxon_ids = galliformes_leaf_tax.taxon_id.values

In [7]:
ods_dir = Path("/data-ssd/alex/datasets/inat-open-data/inaturalist-open-data-20240827")
ods_obs_galliformes = pd.read_csv(ods_dir / "obs_galliformes.csv")

In [8]:
ods_obs_galliformes.sample(5)

,observation_uuid,observer_id,latitude,longitude,positional_accuracy,taxon_id,quality_grade,observed_on
60879,994b78e0-3126-4ce8-afc9-d1b3ad42bc5f,2474058,40.323243,-121.705141,671.0,906.0,research,2013-04-26
160651,46915467-a374-433d-9315-c5470d2891fc,4999766,41.375827,-78.894209,160767.0,906.0,research,2022-09-05
195891,01075349-eeea-4eec-8538-6536fff3a2ee,2227858,34.038627,-106.815223,251.0,1419.0,research,2023-04-29
17587,609a906d-2b2e-472c-bb0d-d904c08444b4,915900,36.446969,74.868263,NaN,846.0,research,2017-05-01
185482,0d35d4ae-2669-46ce-8d6b-d5f2c46d0da9,3409649,8.797553,-82.955688,4.0,2087.0,research,2023-03-21

In [10]:
ods_obs_galliformes.taxon_id.value_counts()

taxon_id
906.0     82008
981.0     25885
1409.0    23026
1204.0    18003
890.0     12251
          ...
820.0        58
1118.0       45
740.0         7
1055.0        4
1181.0        4
Name: count, Length: 122, dtype: int64

In [11]:
!ls {ods_dir}

images		       observations.csv  obs_galliformes.csv  photos.csv
observations_2024.csv  observers.csv	 obs_photos_2024.csv  taxa.csv

In [12]:
ods_photos = pd.read_csv(
    ods_dir / "photos.csv",
    sep="\t",
)

In [14]:
ods_obs_photos_galliformes = pd.merge(
    ods_obs_galliformes,
    ods_photos,
    left_on="observation_uuid",
    right_on="observation_uuid",
    how="left",
)

In [17]:
ods_obs_photos_galliformes.to_csv(
    ods_dir / "obs_photos_galliformes.csv",
    index=False,
)

# now let's do mammals

In [13]:
mammals_dir = Path("/data-ssd/alex/datasets/vision-export-20230412214019-Mammalia-40151/")
mammals_tax = pd.read_csv(mammals_dir / "taxonomy.csv")
mammals_leaf_tax = mammals_tax[~mammals_tax.leaf_class_id.isna()]
mammals_leaf_taxon_ids = set(mammals_leaf_tax.taxon_id.values)

In [14]:
ods_dir = Path("/data-ssd/alex/datasets/inat-open-data/inaturalist-open-data-20240827")
ods_obs = pd.read_csv(
    ods_dir / "observations.csv",
    sep="\t",
    usecols=["observation_uuid", "taxon_id"],
)

In [15]:
ods_obs.dropna(inplace=True)

In [19]:
ods_obs.taxon_id = ods_obs.taxon_id.astype(np.int32)

In [20]:
ods_obs.sample(5)

                               observation_uuid  taxon_id
133487391  000d1935-93ab-4090-8cf1-ce079227c13f    165237
53556586   18faff16-4cc4-4d88-8d4f-fb8993cf17af     49230
78512180   88adb261-6c84-40d2-b553-025d5fcdeeb7    363283
114727936  ab1eef1c-d21f-4c48-a0c6-1d160bab22ac    369020
75937657   88488a3a-89cb-4e46-a46d-1888b4164c1d     49566

In [21]:
mammal_ods_obs = ods_obs[ods_obs.taxon_id.isin(mammals_leaf_taxon_ids)]
len(mammal_ods_obs), len(ods_obs)

(2685382, 156082843)

In [22]:
mammal_ods_obs.to_csv(
    ods_dir / "obs_mammals.csv",
    index=False,
)
# mammal_ods_obs = pd.read_csv(ods_dir / "obs_mammals.csv")

In [25]:
ods_photos = pd.read_csv(
    ods_dir / "photos.csv",
    sep="\t",
    usecols=["photo_id", "observation_uuid", "extension"],
)

In [27]:
ods_obs_photos_mammals = pd.merge(
    mammal_ods_obs,
    ods_photos,
    left_on="observation_uuid",
    right_on="observation_uuid",
    how="left",
)

In [29]:
ods_obs_photos_mammals.to_csv(
    ods_dir / "obs_photos_mammals.csv",
    index=False,
)