In [15]:
from pathlib import Path
import pandas as pd

In [16]:
dataset_dir = Path("/data-ssd/alex/datasets/vision-export-20221020154449-Galliformes-573/")
train = pd.read_csv(dataset_dir / "train_cleaned.csv")
tax = pd.read_csv(dataset_dir / "taxonomy.csv")

In [17]:
train

,Unnamed: 0,filename,photo_id,leaf_class_id,iconic_class_id,taxon_id,weights
0,0,/data-ssd2/alex/images/1e/c3/59311197.jpg,59311197,0,0,1118,1.0
1,1,/data-ssd2/alex/images/70/c9/4866098.jpg,4866098,0,0,1118,1.0
2,2,/data-ssd2/alex/images/95/0c/4793882.jpg,4793882,0,0,1118,1.0
3,3,/data-ssd2/alex/images/20/19/229942605.jpg,229942605,0,0,1118,1.0
4,4,/data-ssd2/alex/images/de/42/64493154.jpg,64493154,0,0,1118,1.0
...,...,...,...,...,...,...,...
66094,66291,/data-ssd2/alex/images/52/5d/225161747.jpg,225161747,121,0,740,0.5
66095,66292,/data-ssd2/alex/images/8d/0e/219066543.jpg,219066543,121,0,740,0.5
66096,66293,/data-ssd2/alex/images/33/07/225161789.jpg,225161789,121,0,740,0.5
66097,66294,/data-ssd2/alex/images/03/3f/219066554.jpg,219066554,121,0,740,0.5
66098,66295,/data-ssd2/alex/images/b8/3f/177646725.jpg,177646725,121,0,740,0.5

In [18]:
tax

,parent_taxon_id,taxon_id,rank_level,leaf_class_id,iconic_class_id,name
0,NaN,1,70,NaN,NaN,Animalia
1,1.0,2,60,NaN,NaN,Chordata
2,2.0,355675,57,NaN,NaN,Vertebrata
3,355675.0,3,50,NaN,NaN,Aves
4,3.0,573,40,NaN,NaN,Galliformes
...,...,...,...,...,...,...
183,2043.0,2105,20,NaN,NaN,Pipile
184,2105.0,2108,10,73.0,0.0,Pipile cumanensis
185,2105.0,2109,10,112.0,0.0,Pipile jacutinga
186,2043.0,2110,20,NaN,NaN,Penelopina
187,2110.0,2111,10,106.0,0.0,Penelopina nigra

In [27]:
for leaf_class_id in range(122):
    taxon = tax[tax.leaf_class_id == leaf_class_id].iloc[0]
    parent_taxon = tax[tax.taxon_id == taxon.parent_taxon_id].iloc[0]
    grandparent_taxon = tax[tax.taxon_id == parent_taxon.parent_taxon_id].iloc[0]
    if taxon.rank_level != 10 or parent_taxon.rank_level != 20 or grandparent_taxon.rank_level != 30:
        print(taxon["name"], taxon.rank_level, parent_taxon["name"], parent_taxon.rank_level, grandparent_taxon["name"])

Polyplectron 20 Phasianidae 30 Galliformes
Tragopan 20 Phasianidae 30 Galliformes
Arborophila 20 Phasianidae 30 Galliformes